<?php

namespace Database\Seeders;

use App\Models\CMS;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class CMSSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        CMS::insert([
            [
                'section' => 'banner',
                'title' => 'Best Bulk SMS Service for Your Business',
                'sub_title' => 'Reliable, fast, and affordable bulk SMS solutions for businesses, organizations, and individuals.Reach your audience instantly with our masking and non-masking SMS services.',
                'image' => 'https://smsmodule.testorbis.com/assets/img/bashboard.jpg',
                'card_title_1' => null,
                'card_title_2' => null,
                'card_title_3' => null,
                'card_title_4' => null,
                'card_subtitle_1' => null,
                'card_subtitle_2' => null,
                'card_subtitle_3' => null,
                'card_subtitle_4' => null,
                'description' => null,
                'question' => null,
                'answer' => null,
                'gmail' => null,
                'phone' => null,
                'address' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'section' => 'featurd',
                'title' => 'Send SMS Campaigns to 1,000+ Mobile Network Operators in More then 200 Countries',
                'sub_title' => 'You can reach your customer from anywherein the world with an SMS service',
                'image' => 'http://127.0.0.1:8000/assets/img/Screenshot_1.png',
                'card_title_1' => null,
                'card_title_2' => null,
                'card_title_3' => null,
                'card_title_4' => null,
                'card_subtitle_1' => null,
                'card_subtitle_2' => null,
                'card_subtitle_3' => null,
                'card_subtitle_4' => null,
                'description' => 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ab inventore ut dignissimos quidem nemo earum eos expedita fuga. Et nisi distinctio, similique recusandae aspernatur, ea saepe, inventore velit quidem ipsam nobis exercitationem corrupti id debitis autem delectus fugiat. Asperiores et fugiat a quisquam repellendus? Veniam, possimus, omnis distinctio corporis nisi corrupti impedit magni consectetur, consequatur odio quo eos ratione odit totam quasi repellat quas eveniet? Ea earum deserunt corrupti. Excepturi corrupti unde consequatur vitae rem temporibus culpa soluta aut. Id saepe nihil, reprehenderit veniam inventore rerum deleniti neque reiciendis dolores recusandae assumenda odio modi et nostrum, quas officiis accusamus possimus? Magnam soluta officia a consectetur veritatis earum ut illo sed neque dolorum eaque repellat, reiciendis sint quas voluptate iste impedit laboriosam debitis cumque. Laborum nemo quas animi exercitationem voluptates error, nesciunt fugiat ducimus perferendis in cum eum quae, velit voluptas repellendus blanditiis saepe quos at illo hic aspernatur autem. Recusandae, quas nemo pariatur, totam mollitia odit esse aspernatur porro molestiae delectus, laborum debitis? Ad illo, reprehenderit praesentium exercitationem voluptatibus recusandae atque. Necessitatibus, ullam, voluptatibus aspernatur sint enim reiciendis possimus ipsa quae consequuntur sapiente quo, quam obcaecati cum? Itaque recusandae reiciendis, repellendus saepe iusto dicta suscipit molestiae, qui et blanditiis quaerat.',
                'question' => null,
                'answer' => null,
                'gmail' => null,
                'phone' => null,
                'address' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'section' => 'about',
                'title' => 'We are a leading provider of bulk SMS services, offering reliable and cost-effective solutions for businesses and individuals.',
                'sub_title' => null,
                'image' => 'http://127.0.0.1:8000/assets/img/about_us.jpg',
                'card_title_1' => 'Complete Language Support',
                'card_title_2' => 'Complete Language Support',
                'card_title_3' => 'Complete Language Support',
                'card_title_4' => 'Complete Language Support',
                'card_subtitle_1' => 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Pariatur, odit quae officiis veritatis aliquid maiores voluptates?',
                'card_subtitle_2' => 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Pariatur, odit quae officiis veritatis aliquid maiores voluptates?',
                'card_subtitle_3' => 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Pariatur, odit quae officiis veritatis aliquid maiores voluptates?',
                'card_subtitle_4' => 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Pariatur, odit quae officiis veritatis aliquid maiores voluptates?',
                'description' => null,
                'question' => null,
                'answer' => null,
                'gmail' => null,
                'phone' => null,
                'address' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'section' => 'faqs',
                'title' => null,
                'sub_title' => null,
                'image' => 'http://127.0.0.1:8000/assets/img/FAQ.jpg',
                'card_title_1' => null,
                'card_title_2' => null,
                'card_title_3' => null,
                'card_title_4' => null,
                'card_subtitle_1' => null,
                'card_subtitle_2' => null,
                'card_subtitle_3' => null,
                'card_subtitle_4' => null,
                'description' => null,
                'question' => 'What is bulk SMS?',
                'answer' => 'Bulk SMS is a service that allows businesses and individuals to send large volumes of SMS messages to multiple recipients simultaneously. It is commonly used for marketing, notifications, and alerts.',
                'gmail' => null,
                'phone' => null,
                'address' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'section' => 'contact',
                'title' => 'Get in Touch',
                'sub_title' => "Have some big idea or brand to develop and need help? Then reach out we'd love to hear about your project and provide help.",
                'image' => null,
                'card_title_1' => null,
                'card_title_2' => null,
                'card_title_3' => null,
                'card_title_4' => null,
                'card_subtitle_1' => null,
                'card_subtitle_2' => null,
                'card_subtitle_3' => null,
                'card_subtitle_4' => null,
                'description' => null,
                'question' => null,
                'answer' => null,
                'gmail' => 'info@example.com',
                'phone' => '+158 996 888',
                'address' => '123 Street 256 House',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
